# COBOL build system Makefile for individual projects

MAKEFILE := $(BUILDDIR)/Makefile

.PHONY: genmk create-dirs clean

genmk: create-dirs $(MAKEFILE)

create-dirs:
	mkdir -p $(BUILDDIR)
	mkdir -p $(TESTRUNDIR)
	mkdir -p $(TARGETDIR)

$(MAKEFILE): build.txt $(GENMK)
	$(GENMK) $@ < $<

clean:
	rm -rf $(BUILDDIR)
	rm -rf $(TARGETDIR)
	rm -rf $(TESTRUNDIR)
	rm -f $(SOURCEDIR)/*~
	rm -f $(COPYDIR)/*~
	rm -f *~
	rm -f test/*~
