# COBOL build system Makefile for individual projects

# targets
#
.PHONY: genmk create-dirs clean

genmk: create-dirs $(GENMAKEFILE)

create-dirs:
	mkdir -p $(BUILDDIR)
	mkdir -p $(TESTRUNDIR)
	mkdir -p $(TARGETDIR)

$(GENMAKEFILE): build.txt $(GENMK)
	$(GENMK) $@ < $<

clean:
	rm -rf $(BUILDBASE)
	rm -rf $(TARGETDIR)
	rm -f $(SOURCEDIR)/*~
	rm -f $(COPYDIR)/*~
	rm -f *~
	rm -f test/*~
